platform :ios, '9.0'

target 'QRScavanger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRScavanger

    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'BEMCheckBox'

end
